bravetechnologycoop/BraveSensor

SessionState.js, SessionStateEnum.js, SessionStateXethruEnum.js, index.js, test/test.js, test/testSessionState.js
Hi Mario,
Here is the start of a set of unit tests for the state machine. To add more tests, add them to tests/testSessionState.js. Hopefully it's clear what is happening in each one. It basically sets the initial state to whatever you tell it to, then you provide the responses to the DB calls that will determine what happened. Then it calls `statemachine.getNextState` and checks the value that it returns against what we expected.
To run the tests locally, just call `npm test`.
To run them on Jenkins, just push your changes.
Other things that I changed to make these unit tests work:
* Factored out the STATE and XETHRUSTATES enums so that I could use them in both the prod code and the test code
* Renamed XETHRUSTATES to XETHRUSTATE to be consistent with the singular STATE constant
* Made …
=> State Machine Unit Tests

db/db.js, index.js
- The /sms endpoint is hit when the Responder phone replies to an alert.
Using the `req.body.From` as the lookup phone number means that we're
using the Responder phone number. This was fine when there was only
a single bathroom per location because the Responder phone would line
up with exactly one bathroom. However, now that we have some locations
with multiple bathrooms, we need to the use the `req.body.To` number
to disambiguate.
- Investigating this bug revealed a lot of test data in the `sessions`
table that I didn't want to change. So instead of updating the
`phonenumber` column in `sessions` (which may also be confusing since
the term `phonenumer` in the `locations` table specifically refers to
the Responder phone number), I instead just changed the query to join
with `locations` …
=> Minimal changes to distinguish between multiple bathrooms at a location (CU-cumnc0)

CHANGELOG.md, package-lock.json, package.json
- Remove explicit dependency on axios because it is no longer used
- Upgraded Twilio to the latest version, which depends on axios
v0.21.1
- Upgraded BraveAlertLib to the latest version, which depends on
the latest Twilio, which depends on axios v0.21.1
This replaces #63 and #64.
=> Remove all references to axios < v0.21.1 (CU-j6yuzk)

Location.js, README.md, Session.js, test/serverTest.js
`devenv-next` was there just while we were waiting for v1.2.0 to be deployed.
=> Merging temporary `devenv-next` into `devenv` where it's supposed to be

sensor-helm-chart/templates/sensor-deployment.yaml
@mariocimet This is what the problem was yesterday. It seems as though it's OK to build with a `.env` in my local, as long as all the environment variables are declared in the deployment.
Maybe we also need a section on updating environment variables since it's now a number of steps...
- Updating your local `.env`
- Letting people know that it's changed
- Updating the `*.env` files on ODetect Admin
- Updating the `sensor-*` secrets on ODetect Admin
- Updating `.travis.yml`
... is there anything else?
=> Tell Helm to get the PG_DATABASE value from the secrets file

index.js
This `i++` was incorrectly changed to just `i` during the linting changes.
=> Increment counter in the watchdog check

CHANGELOG.md, db/redis.js, index.js
Why?
We are having trouble with false positives at Covenant_2 aka 'Youth #111' and suspect that door sensor problems are to blame. Tracking the "control bytes" can help us diagnose it. The control number should increase by one with each door event, so tracking these would reveal if we're missing any requests server side (as opposed to the sensor or argon itself missing events).
See our conversation at https://bravely.slack.com/archives/C0153GVBNGG/p1614800310001600
=> Saving IM21 request control field for debugging door sensor issues (CU-n70k94)

.travis.yml, CHANGELOG.md, README.md
- This will ensure that our images are built in a clean and
consistent environemnt. No chance to anything weird getting
bundled in from our local dev environments
- Also used the prettier format for the README and CHANGELOG. Because of this, you might want to turn on "Hide whitespace changes" in order to see what really changed in thie PR.
- Because I didn't want the push to Digital Ocean to happen unless
the tests and linting pass, I refactored Travis to use staged jobs.
To make this work, I couldn't use the matrix anymore (which we didn't
really need anyways) and I needed to move all the env variables to be
global variables so that they will all be used for every run (in this
case, we only have one run anyways).
- Updated production deployment instructions to use the container that
was …
=> Use Travis to push Docker containers to DO (CU-mrxren)

build.sh
- Since our tags are based on the git commit number, if the tag already
exists in the registry, then the exact code has already been pushed
and doesn't need to be done again.
- This will save us time (by not building and pushing when we don't have
to) and it will decrease the number of times that we pull from Docker
Hub (which as a rate limit of 100 pulls every 6 hours).
What do you think of this? It means that there will be far fewer Docker pushes by Travis, but will it interfere with local dev? It means that you'll need to be sure to update your git commit before pushing each time you want to send up a new version or else it won't do what you think it will. I think that's probably OK since using the same tag more than once with different code _also_ doesn't necessarily do what one would …
=> Only build and push Docker container if it isn't already in the registry (CU-mrxren)

BraveAlerterConfigurator.js, CHANGELOG.md, InnosentStateMachine.js, XeThruStateMachine.js, db/db.js, index.js, package.json, test/serverTest.js, test/testBraveAlerterConfigurator.js, test/testInnosentStateMachine.js, test/testXeThruStateMachine.js
In the end, I'm pretty happy with this `runQuery` function. I'd tried a few different ways of making this boilerplate in the past but didn't like any of them. This feels pretty straightforward though, so I'm happy. The only annoying part was still needing to put the `await runQuery(...)` call inside a `try/catch` because of the `await` in order to avoid potential `Unhandled Promise Rejection Warning`s. Oh well, it's still less copy-and-pasting than before. What do you think?
In line with the transaction boilerplate, I added `try/catch` blocks around all of our uses of actual transactions in the code, including a call to `rollbackTransaction` in the `catch`.
I also took this opportunity to make sure that we are consistently using the `Location` and `Session` object for all DB functions …
=> Do transaction-handling and use Location/Session objects consistently across all DB functions (CU-kry5t5)

BraveAlerterConfigurator.js, CHANGELOG.md, test/testBraveAlerterConfigurator.js
- After the fallback message is sent by brave-alert-lib, it calls
alertSessionChangedCallback with an alertSession object containing
ONLY the session ID and the results from calling Twilio. The code
was taking that and blindly setting the chatbot state and
incidenttype based on that alertSession object, thus setting those
values to null every time the fallback message is sent. Now it tries
to be smarter and will re-save the current values if given undefined
=> Fix alertSessionChangedCallback to not overwrite session with nulls (CU-tnarab)

CHANGELOG.md, index.js
- This will prevent a race condition that was causing never-ending
sessions when a first session (S1) was auto-reset while having
a lock on the sessions table, but then it gave up its lock before
setting start_times[locationid] to null for that location. This
allowed a new session to be created between those two operations
that then had its start_times[locationid] set to null essentially
right after it started. This left us in a position where the
sessionDuration calcuation would return `undefined` and we would
never auto-reset the new session.
Tested this by:
- Running the smoke tests and replying to all the texts
- Running the smoke tests and not replying to any of the texts in order to see the auto-reset happen.
=> Only update start_times array while we have a lock on sessions (CU-vf7z0f)

CHANGELOG.md, Location.js, db/017-add-is-active-to-locations.sql, db/db.js, index.js, mustache-templates/landingPage.mst, mustache-templates/newLocation.mst, mustache-templates/updateLocation.mst, setup_postgresql.sh, test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumberTest.js, test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js, test/integration/BraveAlerterConfiguratorTest/getLocationByAlertApiKeyTest.js, test/integration/serverTest.js
- Inactive locations will not send out duration, stillness, or heartbeat
alerts or change state, but they will still record sensor and vitals
data and will still notify Sentry of low batteries in door sensors
- Locations created through the UI will be ~active~ inactive by default. But existing Locations will be active.
- Added a column on the Landing Dashboard to indicate if a Location
is inactive
- Added a note on the Add A Location page to warn users that newly created Locations will be inactive.
Things I tested:
- Given is_active set to false and no open sessions. When I closed the door and moved around for longer than the duration_timer. Then no session was started, no alerts were sent, and no state changes were logged.
- Given is_active set to false and there is a session and the …
=> Add ability to set Locations to inactive (CU-rk8axg)

CHANGELOG.md, db/db.js, index.js, test/integration/serverTest.js
**Change all endpoints that Particle uses to always return 200**
- Apparently Particle throttles sending messages when it returns too
many 400s and 500s. So to make sure that we're getting all the
message, and since we don't actually do anything with the return
status/message anyways, it seems to make sense to return 200 and
not worry about it.
- Ref: https://docs.particle.io/reference/device-cloud/webhooks/#limits
**Reduce thrown errors in DB functions**
- A few of our DB functions are supposed to return a single object (Location or Session), which means that they use `results.rows[0]`. But if there were no results from the query, there is no `results.rows[0]`, thus throwing an error. Which is  then immediately caught and the very un-helpful error message `{}` is output to the logs.
- …
=> Always send 200 to Particle and reduce thrown errors in DB functions (CU-m0we6c)

CHANGELOG.md, package-lock.json, package.json
- To change `logSentry` to a message instead of an error
- To fix the route in handleTwilioMessage error messages
- ~~Didn't update the CHANGELOG because these two changes are modifications of things that already have an entry in the upcoming release's CHANGELOG.~~
Tested by:
- Deploying to Dev
- Running the smoketests.
- Running the smoketests by replying to the stillness alert using a phone that isn't the Responder phone, which gave me this message: `2021-05-14T02:03:23.945105365Z Bad request to /alert/sms: Invalid Phone Number` 
- Unplugged one of my test devices and saw that it made a Sentry message (not a Sentry exception): `https://sentry.io/organizations/brave-technology-coop/issues/2398137334/?environment=dev-sensor-server&project=3012816&query=is%3Aunresolved` and another one …
=> Update Brave Alert Lib

.vscode/launch.json, CHANGELOG.md
- So that those of us who use VS Code will be able to use it to
debug Mocha tests without any extra work
@mariocimet , after our code review / pair programming session last week, I started thinking that we _shoud_ be able to have a debugger working in VS code. And it didn't actually take much effort to make this work. Wish I'd done it much earlier. 
This adds two run configurations. One which runs all the tests in the `/test` folder and the other which runs all the tests in the currently-open file.
All you need to do is open up the "Run and Debug" View, by clicking on the 
icon in the left menu, then you can select which of those Run configurations you want to use in this dropdown menu:
and push the "Play" button.
Then, it will run the tests and stop at any breakpoints that you've set in …
=> Add VSCode launch config for debugging Mocha tests

.travis.yml, CHANGELOG.md, audit-ci.json
- This will block the build when there are high or critical security
issues. The build will only pass if these issues are added to the
allowlist in audit-ci.json or fixed.
- :heavy_check_mark: With no changes in the project
- :heavy_check_mark: See in the Travis logs that it ran (https://app.travis-ci.com/github/bravetechnologycoop/BraveSensor-Server/jobs/525028217)
- :heavy_check_mark: Travis passes
- :heavy_check_mark: Add a known low severity security issue to the project
- :heavy_check_mark: See in the Travis logs that it ran (https://app.travis-ci.com/github/bravetechnologycoop/BraveSensor-Server/jobs/525028875)
- :heavy_check_mark: Travis passes
- :heavy_check_mark: Add a known high severity security issue to the project 
- :heavy_check_mark: See in the Travis logs that it ran …
=> Add audit-ci to Travis to perform static security checks (CU-121j22d)

AlertReasonEnum.js, BraveAlerterConfigurator.js, CHANGELOG.md, README.md, Session.js, db/019-change-alert-reason-values.sql, db/020-add-responded-at-to-sessions.sql, db/db.js, index.js, mustache-templates/locationsDashboard.mst, package-lock.json, package.json, setup_postgresql.sh, stateMachine/StateMachine.js, test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumberTest.js, test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js, test/integration/dbTest/getHistoricAlertsByAlertApiKeyTest.js, test/integration/serverTest.js, test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js, test/unit/BraveAlerterConfiguratorTest/getHistoricAlertsByAlertApiKeyTest.js, test/unit/BraveAlerterConfiguratorTest/getReturnMessageTest.js, test/unit/StateMachineTest.js
- Use alert_type_enum in DB and from Alert Lib instead of strings:
- To better conform with our [desired shared DB schema](https://docs.google.com/document/d/1k-xkWnR7xoWRi6gEiN8p-nda5bhxDvOqNYCtPNi7OwY/edit)
- So that we don't need to translate between the AlertReasonEnum.js values here and the alertTypeEnum.js values in BraveAlertLib
- Add `responded_at` to Sessions
- So that we can display it on the Alert App
- Also changed the `db.js` functions around saving sessions to be more like the way that Buttons does it for more consistency between the two code bases and so that we only need one DB function for saving sessions instead of two.
- Add `GET /alert/historicAlerts` endpoint
- For use in the Alert App
- Add corresponding tests
- :heavy_check_mark: Run the smoke tests
- …
=> Add GET /alert/historicAlerts endpoint and `sessions.responded_at` column (CU-hjwfx2)

CHANGELOG.md, IM21DoorStatusEnum.js, README.md, im21door.js, index.js, smokeTest.js, stateMachine/StateMachine.js, test/integration/serverTest.js, test/unit/im21doorTest.js
- We were relying on specific, hardcoded values for the signal coming in from the IM21 door sensor. However, the IM21 specs explain the value as a bit map. Changed the code to use similar logic.
- This fixes a problem where we were missing Door Open and Door Close events that occur when the battery is low
- No longer stores 'LowBatt' as a door signal value in Redis because this was only ever working when it was a low battery and the door was closed. It would not have worked if the door were open. We also weren't using this information for anything that I can see.
- Rename DOOR_STATUS to DOOR_STATE wherever it's used for consistency with the `SessionStateDoorEnum.js` file and the other places where the enum is used.
- Added a Sentry log if the door sensor sends us the tamper bit on.
- …
=> Fix IM21 door signal processing (CU-4avrue)

.vscode/launch.json, server/BraveAlerterConfigurator.js, server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js
- Also updated the tests for this function to better match the tests in
Buttons because I think the Buttons tests were written better for what
ended up being the implementation of this function. The tests that were
here in Sensors looked like they belonged with an older implementation
that we didn't end up using.
- :heavy_check_mark:  Deploy to `dev.sensors.brave.coop`
- :heavy_check_mark: Run the smoke tests
- :heavy_check_mark:  Trigger an alert on my XeThru+Argon device and see the respondedAt value is `null`
- :heavy_check_mark: Respond 'OK' and see the respondedAt value change to the current time on the Dashboard
- :heavy_check_mark: Respond to the incident category question with a valid incident category and see the respondedAt value does not change
- :heavy_check_mark: Respond to …
=> No longer update Responded At when given an invalid incident category (CU-1ae1j60)

CHANGELOG.md, server/.env.example, server/package-lock.json, server/package.json, server/sensor-helm-chart/templates/sensor-deployment.yaml
- :heavy_check_mark:  Deploy to `dev.sensors.brave.coop`
- On Android
- :heavy_check_mark: Custom sound used for push notifications when Alert App is in the foreground
- :heavy_check_mark:  Custom sound used for push notifications when Alert App is closed
- :heavy_check_mark:  Custom sound used for push notifications when Alert App is in the background
- :question:  Custom sound stops when the the app is opened (this seems to work when I use the notification to open it, but not when I open it through the normal app)
- :question: (didn't check on iOS because it should behave the same as Buttons https://github.com/bravetechnologycoop/BraveButtons/pull/121) On iOS
- :question: Custom sound used for push notifications when Alert App is in the foreground
- :question: Custom sound used for push …
=> Add custom sound to push notifications by updating brave-alert-lib (CU-10xfkhr)

CHANGELOG.md, server/.env.example, server/BraveAlerterConfigurator.js, server/db/025-add-notifications.sql, server/db/db.js, server/setup_postgresql.sh, server/test/integration/BraveAlerterConfiguratorTest/getNewNotificationsCountByAlertApiKeyTest.js
this pull request adds the Sensors backend implementation of the notification counting feature used in the Alert App.
testing notes:
- the automated tests passed on Travis when I pushed the branch
- I tested this on an Android emulator connected to the Sensors dev environment and everything seemed to work as expected.
=> add GET /alert/newNotificationsCount endpoint (CU-hjwcwk)

CHANGELOG.md, server/README.md, server/index.js, server/smokeTest.js
- :heavy_check_mark: Deploy on Dev
- :heavy_check_mark: Run the smoke tests and do not respond to any texts
- :heavy_check_mark: Verify that the 'SmokeTestLocation' is configured with XeThru and SSM for the first test
- :heavy_check_mark: Verify that the 'SmokeTestLocation' is configured with INS and FSM for the first test
- :heavy_check_mark: Receive texts and see updates as expected in Dashboard and server logs for XeThru + SSM
- :heavy_check_mark: Receive texts and see updates as expected in Dashboard and server logs for INS + FSM
- :heavy_check_mark: Run the smoke tests and respond to all the texts
- :heavy_check_mark: Receive texts and see updates as expected in Dashboard and server logs for XeThru + SSM
- :heavy_check_mark: Receive texts and see updates as expected in Dashboard and …
=> Add an INS firmware state machine smoke test (CU-1tdbnjg)

CHANGELOG.md, server/Location.js, server/dashboard.js, server/db/027-add-location-created-and-updated-dates.sql, server/db/db.js, server/mustache-templates/updateClient.mst, server/setup_postgresql.sh, server/test/integration/dashboardTest/submitEditClientTest.js, server/test/integration/dashboardTest/submitEditLocationTest.js, server/test/integration/dashboardTest/submitNewClientTest.js, server/test/integration/dashboardTest/submitNewLocationTest.js, server/test/unit/vitalsTest/checkHeartbeatTest.js
- :heavy_check_mark: Add a new client with leading, trailing, and internal whitespace for all values where this is possible through the UI. See that
- :heavy_check_mark: client is added in DB without the leading and trailing whitespace
- :heavy_check_mark: Try to add a new client with only whitespace for each value individually for all values where this is possible through the UI. See that
- :heavy_check_mark: client cannot be added if the value was required
- :heavy_check_mark: uses 'null' when the value was not required
- :heavy_check_mark: Add a new client with an existing `displayName` but with leading and trailing whitespace. See that
- :heavy_check_mark: client cannot be added
- :heavy_check_mark:  Edit an existing client with leading, trailing, and internal whitespace for all …
=> Trim all values when adding or editing Clients and Locations through the API (CU-1pdmvee)

CHANGELOG.md, server/Location.js, server/RadarTypeEnum.js, server/dashboard.js, server/db/029-drop-location-radartype.sql, server/db/InnosentData.js, server/db/db.js, server/db/redis.js, server/index.js, server/mustache-templates/newLocation.mst, server/mustache-templates/updateLocation.mst, server/routes.js, server/setup_postgresql.sh, server/smokeTest.js, server/stateMachine/StateMachine.js, server/stateMachine/stateMachineHelpers.js, server/test/integration/dashboardTest/submitEditLocationTest.js, server/test/integration/dashboardTest/submitNewLocationTest.js, server/test/integration/serverTest.js, server/test/unit/StateMachineHelpersTest.js, server/test/unit/vitalsTest/checkHeartbeatTest.js, server/testingHelpers.js, server/vitals.js
- `/api/devicevitals` was originally intended to allow us to display signal strength on the dashboard, but was never fully implemented and is not currently being used at all (i.e. no devices are actually calling this endpoint).
- We decided awhile ago to skip over Sensors v3.0 (INS + SSM). This means that right now, all SSM sensors are XeThru and all FSM sensors are INS. So we don't need any of the state machine code on the backend for INS radars. This meant that we could remove the `radar_type` column from the DB, the `innosent:*` key from Redis, and the `/api/innosent` API endpoint that was intended to be called be a Particle webhook.
- :heavy_check_mark: Deploy to Senors Dev
- :heavy_check_mark: Run smoketests
- :heavy_check_mark: Create real alerts in my bathroom
- :heavy_check_mark: …
=> Remove `/api/devicevitals` and everything everything that is only used in Sensors v3.0 (INS + SSM)

CHANGELOG.md, firmware/boron-ins-fsm/src/debugFlags.h, firmware/boron-ins-fsm/src/im21door.cpp, firmware/boron-ins-fsm/src/im21door.h, firmware/boron-ins-fsm/src/stateMachine.cpp
When debugging publishes are turned on, publish the raw advertising data from the door sensor whenever it sends a heartbeat. 
Testing that is done: 
- When door sensor sends a heartbeat, the particle console receives 1-4 publishes of the door sensor raw data, and that data is of expected values. 
- When publishes are off, door sensor does not publish heartbeats.
=> Improved Door Heartbeat Debug Publishes (CU-2chv6je)

CHANGELOG.md, server/BraveAlerterConfigurator.js, server/README.md, server/test/unit/BraveAlerterConfiguratorTest/getReturnMessageToRespondedByPhoneNumberTest.js
1. Change incident category message text
- It was brought up at Team Time today that sometimes users think
they need to give an incident category as soon as the question
is asked, but they don't know the answer yet, so they will just
enter in whatever they feel like instead of waiting until they
know the real incident type. This small text change will hopefully
imply that they shouldn't reply until they have responded to the
request for help
2. Updated production deployment instructions in the README
- Based on a couple of deployments where we actually did things a
little bit differently than described 
- Firmware compilation sometimes takes a long time, so we can start
it before working on the server deployments and then do them in
parallel if it's taking awhile
- Added instructions on …
=> A couple of things that don't have Tasks

CHANGELOG.md, server/dashboard.js, server/db/038-add-client-extension-table.sql, server/db/db.js, server/setup_postgresql.sh
- Used an extension table because this data is only every used by
the CSV export and I didn't want to have to alter the Client
object to add fields that aren't used anywhere else in the
program. This also gives the flexibility to easily add and remove
columns in this table for this need as more reporting requirements
come up or change
- For now, it is an MVP and is not included
on the New Client or Update Client pages. If it is missing when
someone does the CSV export and they need it filled in, they
can ask someone to add it to the DB
- Just used the `text` datatype to keep this super flexible for now. If we find that it's a problem later, we can introduce an `enum` type.
- :heavy_check_mark: Deploy to Dev
- :heavy_check_mark: Run smoke tests
- :heavy_check_mark: Export CSV
- …
=> Add Country, Country Subdivision, and Building Type to CSV Export (CU-2c6crcn)

CHANGELOG.md, server/BraveAlerterConfigurator.js, server/dashboard.js, server/db/db.js, server/package-lock.json, server/package.json, server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumbersTest.js
- When an SMS arrives from a phone, use both the fromNumber and the
toNumber to determine the most recent session instead of just the
toNumber. The toNumber should match one of the Sensors' phone number
and the fromNumber should match one of the clients'
responderPhoneNumbers. If there is one that works for both, then it's
the right session, if not, then it didn't find any
- Note that an SMS can come from any of the client's
responderPhoneNumbers, not just the one that initially responded to
the session
- :heavy_check_mark: Deploy to Dev
- :heavy_check_mark: Run smoketests
- Set up two clients as follows:
- Client 1:
- ResponderPhoneNumber: My phone number
- Location A:
- TwilioPhoneNumber: Valid dev Twilio number
- Client 2:
- ResponderPhoneNumber: James' phone number
- Location B:
- …
=> Allow Twilio numbers to be shared across clients (CU-2fk3y8a)

CHANGELOG.md, server/vitals.js
- These are annoying and happen regularly as new Sensors are
being provisioned. Still log them to file because they may still
indicate something wrong with our configuration, but for the most
part, these have been happening during expected situations and
causing a lot of headaches
- :heavy_check_mark: Deploy to dev
- :heavy_check_mark: Run smoketests
- :heavy_check_mark: Send a heartbeat from an unknown Particle core ID using Postman
- :heavy_check_mark: See the message is logged to the server 
- :heavy_check_mark: Do NOT see the message logged to Sentry
=> Remove Sentry logs for heartbeats from unknown Particle core ID (CU-2ju4ky8)

.travis.yml, CHANGELOG.md, server/api.js, server/routes.js, server/test/integration/apiTest/getAllSensorsTest.js, server/test/integration/apiTest/getSensorTest.js
- To be used by the new Dashboard in PA
- Wanted to do this one first because it will unblock my table creation in PA
=> Add `GET /api/sensors` and `GET /api/sensors/:sensorId` routes (CU-2chw9e3)

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/imDoorSensor.cpp, firmware/boron-ins-fsm/src/stateMachine.cpp, server/test/integration/vitalsTest/handleHeartbeatTest.js, server/testingHelpers.js, server/vitals.js
- Because the Boron doesn't have a clock that keeps actual time, the millis() function returns the number of milliseconds since the device started/restarted. We were using this to calculate the last time that we saw a message from the door sensor. This works fine as long as we have seen at least one door message since the device last started up. In the case where we haven't seen any door messages yet, then it will return simply the number of milliseconds since the start up. This is almost certainly going to be less than the number of milliseconds since the actual last door message, and there is no way for the Boron to know how long its been since the last time because it's starting with no information. However, the DB has been tracking this information. So by sending '-1' when the Boron …
=> Change the door last seen behaviour (CU-34atvnc)

CHANGELOG.md, server/audit-ci.json, server/package-lock.json, server/package.json
- Which has the latest version of Twilio node, so was able to remove the audit-ci exception
=> Upgrade Brave Alert Lib (CU-860phzbq5)

CHANGELOG.md, server/resources/translations/common.en.json
twilio doesn't like it, so we're changing it to a youtube link : (
testplan:
=> change bit.ly link in SMS message (CU-2mddwpd)

server/dashboard.js
=> Don't display locations on Vitals page if client.isDisplayed is false (CU-860ptt5rp)

CHANGELOG.md, server/dashboard.js, server/mustache-templates/newClient.mst, server/mustache-templates/updateClient.mst, server/test/integration/dashboardTest/submitEditClientTest.js, server/test/integration/dashboardTest/submitNewClientTest.js
- It is a valid use case to have this field be an empty array. In this case, only the Responder Phone Numbers will receive vitals text messages. Before this code change, we would need to make this happen directly in the DB, which carries the risk of human error. This will be better, and it wasn't a complicated change, so it was worth doing even though the Dashboard is supposed to move to PA
=> Allow heartbeatPhoneNumbers to be empty from the Dashboard (CU-2uad09a)

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/stateMachine.cpp
- On the very first initialization of v9.4.0, the Long Stillness Timer value in EEPROM was begin set correctly to the current value of the previously-only Stillness Timer. But then that value wasn't being copied into the variable that was used in the State Machien to determine whether the threshold had been hit *doh*. So added that in
- And add more information to the debug mode messages
=> Fix inititalization of Long Stillness Timer (CU-860r11fng)

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/consoleFunctions.cpp, firmware/boron-ins-fsm/src/debugFlags.cpp, firmware/boron-ins-fsm/src/debugFlags.h, firmware/boron-ins-fsm/src/stateMachine.cpp, firmware/boron-ins-fsm/src/stateMachine.h, firmware/boron-ins-fsm/test/base.h
- Debug publishes will automatically turn off after 8 hours so that we don't end up accidentally leaving it on for days at a time, using up all our Particle data operations
- Removed the `stateMachineDebugFlag` from stateMachine.h and just included `debugFlags.h` instead. That will reduce the repetition
- Moved `lastDebugPublish` into `debugFlags.h` to keep all the debug-related things together and to clarify that it is a global variable
- Moved the `DEBUG_PUBLISH_INTERVAL` constant into `debugFlags.h` also to keep all the debug-related things together
=> Add auto-off for debug messages (CU-860r0z9zb)

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/imDoorSensor.cpp, firmware/boron-ins-fsm/src/imDoorSensor.h, firmware/boron-ins-fsm/src/stateMachine.cpp, server/SensorsVital.js, server/dashboard.js, server/db/042-add-tamper-flag.sql, server/db/db.js, server/mustache-templates/clientVitals.mst, server/mustache-templates/vitals.mst, server/resources/translations/common.en.json, server/test/integration/vitalsTest/handleHeartbeatTest.js, server/testingHelpers.js, server/vitals.js
Track the door sensor tamper flag and alert about it
- When the firmware doesn't know the value of the tamper flag, it sends
-1, to match what we do about the time since last door message
- Changed the door low battery flag to also sent -1 if it is unknown, to
be consistent with the others. It was probably giving us fake
battery-no-longer-low messages the way that it was before
- Changed firmware to use binary values `0b0100` instead of the bitwise
operation `(1 << 2)` to save on execution cycles and because I think
that it's just as clear what it means that way
- Updated the DB to store the latest tamper flag in the sensors_vitals
and sensors_vitals_cache tables
- Updated the dashboard to show the latest Tamper flag value on the
Vitals pages
- Sends a message to the Responder and …
=> Alert when the door sensor has been tampered with (CU-860pp0zfn)

CHANGELOG.md, server/index.js
- These CORS options were being added by our Kubenetes nginx ingress, but since we aren't going to be using Kubernetes anymore, it now needs to be done by Express
- The defaults used by Kubenetes are explained here: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#enable-cors
- This solution came from https://stackoverflow.com/questions/32659139/how-to-overcome-access-control-allow-origin-error-when-client-talks-to-server#answer-32748086
=> Add CORS configuration to Express Proxy Middleware

CHANGELOG.md, firmware/boron-ins-fsm/src/BraveSensorProductionFirmware.ino, firmware/boron-ins-fsm/src/stateMachine.cpp, firmware/boron-ins-fsm/src/stateMachine.h, server/test/integration/vitalsTest/handleHeartbeatTest.js, server/vitals.js
The firmware keeps track of the previous 3 heartbeats and whether or not they missed door events. If >1 of the last 3 heartbeats missed door events, `doorMissedFrequently` will be set to true in the JSON data published to Particle.
`vitals.js` handles `/api/heartbeat`, and upon receiving this data from the sensor, will check if `doorMissedFrequently` is set to true; if yes, a Sentry log will be sent.
Test plan:
=> Sentry log for sensor frequently missing door events (CU-860rk8v2a)

CHANGELOG.md, server/package-lock.json, server/package.json
- Upgraded Chai to newer version to resolve security vulnerabilities.
- Upgraded brave-alert-lib because newer version exists.
=> Upgrade Chai and brave-alert-lib (CU-8678wgn0p)

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/consoleFunctions.cpp, firmware/boron-ins-fsm/src/consoleFunctions.h, firmware/boron-ins-fsm/src/stateMachine.cpp, firmware/boron-ins-fsm/src/stateMachine.h, firmware/boron-ins-fsm/test/consoleFunctionTests.cpp, server/BraveAlerterConfigurator.js, server/Session.js, server/db/db.js, server/package-lock.json, server/package.json, server/particleFunctions.js, server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js, server/test/unit/ParticleFunctionsTest/resetStillnessTimerTest.js, server/testingHelpers.js
- Create a new Particle cloud function that when called will reset the current Stillness Timer value, thus changing the state machine to wait at least another Stillness Threshold seconds before the next Stillness Alert
- Call this new cloud function whenever a Responder first responds to an alert
=> Reset Stillness Timer (CU-860rbtg4k)

CHANGELOG.md, server/api.js, server/db/db.js, server/routes.js, server/test/integration/apiTest/messageClientsTest.js
This API call is for sending downtime messages or other things that responders should know about.
It works as follows:
For all clients that are sending vitals, sending alerts, and have at least one location that is sending vitals and sending alerts: send a Twilio message containing the message that was posted.
Requires proper submission of the Particle Accelerator API key (braveKey); this is because the API call is intended to be called from PA.
Upon successful submission of the API key, the server will respond with a JSON object containing information about contacted/failed clients:
```json
{
"status": "success",
"message": "This is the text message that was sent!",
"contacted": [
{
"to": "+11111111111",
"from": "+12222222222",
"clientId": "01234567-89ab-cdef-0123-456789abcdef", …
```
=> Implemented API call /api/message-clients (CU-w9bcb5)

CHANGELOG.md, server/api.js, server/test/integration/apiTest/messageClientsTest.js
Upon porting this feature to the BraveButtons repository, I discovered that the response object returned by /api/message-clients does not match the conventions described at the top of the api.js file in this repository.
This PR does not change the functionality of this API request; it simply moves some of the response object under a `data` object. Please read the conventions information at the top of api.js for more information.
Test Plan:
=> Fixed response object of /api/message-clients to match conventions

CHANGELOG.md, firmware/README.md, firmware/boron-ins-fsm/src/BraveSensorProductionFirmware.ino, firmware/boron-ins-fsm/src/consoleFunctions.cpp, firmware/boron-ins-fsm/src/consoleFunctions.h, firmware/boron-ins-fsm/src/flashAddresses.h, firmware/boron-ins-fsm/src/imDoorSensor.cpp, firmware/boron-ins-fsm/src/imDoorSensor.h, firmware/boron-ins-fsm/src/stateMachine.cpp, firmware/boron-ins-fsm/src/stateMachine.h, firmware/boron-ins-fsm/test/base.h, firmware/boron-ins-fsm/test/consoleFunctionTests.cpp
Adding an additional entrance condition from state0 to state1.
- if the state0 timer exceeds a maximum timeout window, the firmware cannot enter state1
- this timer is reset when the paired door sensor switches from an open to a closed status
- the default value for the timeout will be 1 hour for uninitialized firmware
- a particle console function can be used to change the timeout value
- the console publish message will contain the current timer count for state 0 in `timer_status` along with the timeout in `window_size`
___
Oct 11th, 2024:
Ensure that the timer resets in these cases:
Ensure that the timer does NOT reset in these cases:
=> Timeout "Window" in state 0 for allowable entrance into state 1 (CU-8678t4ztg)

CHANGELOG.md, server/BraveAlerterConfigurator.js, server/db/db.js, server/test/integration/vitalsTest/handleHeartbeatTest.js, server/test/unit/vitalsTest/checkHeartbeatTest.js, server/vitals.js
Made some small changes to see if they will have any effect on the increased deadlock errors that have been coming in. I will monitor the Sentry error logs after these changes are deployed, then revisit to amend/update. Changes are outlined below and in the clickup task comments. I don't _think_ I need to add new tests for these changes, but let me know if you think otherwise.
**vitals.js**
- Added error handling to `sendLowBatteryAlert()` to stop subsequent db queries  
**BraveAlerterConfigurator.js**
- Added retry to `alertSessionChangedCallback()` per convo with Theresa 
- Retrying `beginTransaction` as we only have on shot at this function working (vs heartbeat that comes in often and can capture data the next time its called) 
- Retry has no time delay as of right now, but could be …
=> Deadlock bug fixes (CU-8678wudz8)

CHANGELOG.md, server/package-lock.json, server/package.json
`axios` must be upgraded because of a critical security vulnerability raised by `npm`.
This is a breaking version change, so this PR outlines the additional testing that I have done to ensure the functionality of this repository isn't broken by upgrading `axios`.
Test Plan:
=> Upgrade axios from 0.21.4 to 1.6.0

CHANGELOG.md, server/db/db.js, server/pa.js, server/routes.js, server/test/unit/paTest/handleCheckDatabaseConnection.js, server/test/unit/paTest/handleCheckDatabaseConnectionTest.js
This PR is part of the broader Clickup task to create a system status page in PA. These changes include creating a route to check if the BraveSensors database connection is working as expected (by running one simple db query). PA will hit this route with a `googleIdToken` and `braveKey`. Upon getting the response, PA will  display a green icon if the connection is working or a red icon if it is not. 
- Unit Test for `pa.handleCheckDatabaseConnection`
- Other Testing
=> Add Route to Check the Database Connection (CU-86dqkw7ef)

CHANGELOG.md, firmware/boron-ins-fsm/src/stateMachine.cpp
This pull request removes the condition of `!hasDurationAlertBeenSent` when triggering a duration alert. `state2_duration_timer` is also zeroed to the current clock time upon triggering a duration alert.
---
Test Plan:
=> Allow Duration Alerts to Repeat (CU-8678tmmew)

CHANGELOG.md, server/package-lock.json, server/package.json
The updates to brave-alert-lib does not concern BraveSensor just yet; it allows PA to be authorized with the Authorization header, in addition to submission of Google ID Token in the body of a post request.
=> Upgrade brave-alert-lib to v12.3.0 (CU-13kqjz8).

.travis.yml
Travis environment is depending on the mongodb-org which has an expired signing key. Luckily this error is only in the firmware linting step. As we're hoping to migrate to GitHub Actions for testing in the future, I'd rather replace this step with a suggestion that devs run linting scripts themselves in good faith, rather than wait for Travis to resolve this 😓 .
=> Fix Travis firmware linting step mongodb-org error

CHANGELOG.md, server/dashboard.js, server/db/db.js, server/test/integration/vitalsTest/handleHeartbeatTest.js, server/testingHelpers.js, server/vitals.js
Changed logSensorsVitals and getMostRecentSessionWithDeviceid to use location instead of it's id so it does not need to call getLocations. Also changed the test cases to reflect that.
Test Plan
=> Minimized getLocations call (CU-86dqq93dp)

CHANGELOG.md, server/dashboard.js, server/mustache-templates/landingPage.mst
Previously, the dashboard would display all sensors, we suspect that this may be what is causing the load times to be so long.
Removed the sensors on the dashboard, they will still be viewable through the client page.
=> Only display clients on the dashboard

CHANGELOG.md, firmware/boron-ins-fsm/src/imDoorSensor.cpp
This PR adds a BLE id prefix for the latest batch of IM21 door sensors. This is required for the new batch of door sensors to be able to pair with the main sensor unit.
___
Test Plan:
=> New door sensor prefix for recent batch order (CU-86duk2kpg)

CHANGELOG.md, server/dashboard.js, server/db/db.js, server/mustache-templates/newClient.mst, server/test/integration/dashboardTest/submitEditClientTest.js, server/test/integration/dashboardTest/submitNewClientTest.js
- Changed the sensors dashboard to make the fallback numbers optional for new and edit client
- Updated db query calls to handle empty array for fallback numbers
- Database defaults to {} empty array if we pass empty or undefined parameters for fallback numbers
- Added test cases for a request that contains valid non-empty fields but with no fallbackPhoneNumbers for both new client and edit client functions
=> Make fallback number optional for Sensors dashboard (CU-86du49q25)

CHANGELOG.md, server/dashboard.js, server/db/053-alter-deviceType-enum.sql, server/db/db.js, server/index.js, server/mustache-templates/clientPage.mst, server/mustache-templates/newLocation.mst, server/mustache-templates/updateLocation.mst, server/pa.js, server/package-lock.json, server/package.json, server/test/integration/dashboardTest/submitEditLocationTest.js, server/test/integration/dashboardTest/submitNewLocationTest.js, server/test/integration/dbTest/getActiveSensorClientsTest.js, server/test/unit/vitalsTest/checkHeartbeatTest.js
- Updated **brave-alert-lib to v15.0.4** for deviceType enum change
- Added migration script (migrationID 53) to update device_type_enum to handle multi-stall and single-stall sensors separately.
- Updated device_type_enum to have 'DEVICE_SENSOR_SINGLESTALL' and 'DEVICE_SENSOR_MULTISTALL' instead of 'DEVICE_SENSOR'. <br></br>
- Updated the following db functions: getActiveSensorClients(), getLocations(), createLocationFromBrowserForm(), getDataForExport(), getLocationsFromClientId(), createLocation(), getRecentSensorsVitals() and getRecentSensorsVitalsWithClientId()
- Added functionality to dashboard for submit new location and edit location to handle different device_types using dropdown select 
- Updated test cases for newLocation and updateLocation to use both sensor types
- Wrote new …
=> Make sensor server code compatible with multiple sensor types (CU-86duvwbq2)

CHANGELOG.md, firmware/boron-ins-fsm/src/BraveSensorProductionFirmware.ino, firmware/boron-ins-fsm/src/consoleFunctions.cpp, firmware/boron-ins-fsm/src/consoleFunctions.h, firmware/boron-ins-fsm/src/flashAddresses.h, firmware/boron-ins-fsm/src/stateMachine.cpp, firmware/boron-ins-fsm/src/stateMachine.h, firmware/boron-ins-fsm/test/base.h, firmware/boron-ins-fsm/test/consoleFunctionTests.cpp
This is replacing the High/Low Confidence thresholds with the main difference being that "low confidence" stillness is being removed and "High Confidence" stillness is the default stillness. The "low confidence" threshold will remain as the entry condition for occupation
The firmware update must account for High/Low Confidence settings that are already tuned in production devices that have fw version 1924.
If the firmware that is updated did not have high/low confidence tunings, set the default occupant detection threshold to the same value as the INS threshold
Test Plan:
___
Initialization:
Functionality:
=> Occupant Detection INS Threshold (CU-86dvnjxk7)
