db/000-template.sql
db/001-setup.sql
db/002-hypertable.sql
db/db.js
index.js

also deleted a redundant getEnvVar, added template for db migrations, and included a db migrations script

switching to remote managed db

---

setup_server.sh

needs to be tested, but this fix worked for the Brave Buttons chatbot server.

fixed certificate renewal

---

README.md
build_dev.sh
build_prod.sh

Hi folks - This is an initial commit only, definitely looking for more feedback on anything I may have missed as well as the overall structure of the repo's README before we merge this.

Updated README with kubernetes and docker deployment notes CU-d4n7av

---

README.md

- Missed a step in the front-end instructions. Need to make sure that it's directing to the correct server
- Had the wrong instructions on where to find the value for the REDIS_CLUSTER_IP value

Fix README instructions (front-end and redis IP)

---

CHANGELOG.md
IM21DoorStatusEnum.js
Location.js
db/009-add-particlecoreid-to-locations.sql
db/db.js
db/redis.js
index.js
package-lock.json
setup_postgresql.sh
test/serverTest.js

This PR implements functionality to handle and store door sensor data from the IM21 sensors and the Particle Device vitals on the Redis Database.

CU-h2y2nt im21 endpoint

---

Location.js
README.md
Session.js
test/serverTest.js

- Remove commas from `Location.js` and `Session.js`
- Update some references to ODetect to reflect name change to Brave Sensor

Remove commas/clean-up (CU-k725tk)

---

CHANGELOG.md
index.js

- Change `location_human` to `display_name` to match db and fix display issue

Fix Fallback Message (CU-mgz8vq)

---

.env.example
.gitignore
.travis.yml
CHANGELOG.md
README.md
db/db.js
sensor-helm-chart/.helmignore
sensor-helm-chart/Chart.yaml
sensor-helm-chart/templates/NOTES.txt
sensor-helm-chart/templates/_helpers.tpl
sensor-helm-chart/templates/sensor-deployment.yaml
sensor-helm-chart/templates/sensor-service.yaml
sensor-helm-chart/values.yaml
setup_postgresql.sh

allows for a different username and database for postgresql

---

index.js

- Remove distance from xethru validation as it caused issues on dev
- @mariocimet and I watched the logs running for a live session in my bathroom and tested that texts are working again

Remove distance from xethru validation (CU-hx0jjc)

---

CHANGELOG.md
index.js
test/serverTest.js

This will result in us getting notifications when they go down, not just when they come back on.

checkHeartbeat running every second independently of incoming sensor data (CU-p34wcw)

---

CHANGELOG.md
README.md
db/db.js
index.js
package-lock.json
package.json
smokeTest.js
test/serverTest.js
testingHelpers.js

Check it out, this is running on the staging deployment. To run the smoke test, use the following command:
`node smokeTest 'https://staging.odetect.brave.coop/'  '<your phone>' '<valid twilio number for our account>'`
The desired behavior is the creation of a session which gets closed, and then a session which generates an alert. The procedure I have in mind is checking the phone that you gave as a parameter, as well as the front-end for the sessions.
I also like to look at the logs on the server with 
`kubectl logs -f deploy/staging-sensor-server`.
I will note that I get 'bad request sender is not twilio' for this 🤔.

Added a smoke testing script with setup and teardown endpoints. (CU-kcxndt)

---

db/redis.js

the goal with this is bounded and predictable memory usage, compared to the unpredictable behavior that results in exceeding our memory limits and for example, the door stream for a location being deleted

added max length to function that populates xeThru redis stream CU-p34wbb

---

CHANGELOG.md
Location.js
db/012-drop-unused-locations-columns.sql
db/013-update-locations-table-for-forms.sql
db/db.js
db/redis.js
index.js
mustache-templates/landingPage.mst
mustache-templates/locationFormCSSPartial.mst
mustache-templates/locationsDashboard.mst
mustache-templates/navPartial.mst
mustache-templates/newLocation.mst
mustache-templates/updateLocation.mst
setup_postgresql.sh
smokeTest.js
test/serverTest.js
test/testBraveAlerterConfigurator.js

- Added add and update forms and routes for location
- Removed/renamed db columns (from [this task](https://app.clickup.com/t/gez8x0))
I still need to write some tests but wanted to touch base with folks tomorrow on a few things first, mainly as regards what's actually mandatory and where checks should be done

Add/Update Location Forms (CU-m72ted)

---

CHANGELOG.md
sensor-helm-chart/templates/sensor-deployment.yaml
sensor-helm-chart/templates/sensor-service.yaml

- When the image.tag value was all digits, for example `9285070`, this
was throwing a big error message:
```
Error: UPGRADE FAILED: cannot patch "dev-sensor-server" with kind Deployment:  "" is invalid: patch: Invalid value: "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"deployment.kubernetes.io/revision\":\"4\",\"meta.helm.sh/release-name\":\"dev\",\"meta.helm.sh/release-namespace\":\"default\"},\"creationTimestamp\":\"2021-05-04T19:43:12Z\",\"generation\":4,\"labels\":{\"app.kubernetes.io/instance\":\"dev\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"sensor-server\",\"app.kubernetes.io/version\":\"3.2.0\",\"helm.sh/chart\":\"sensor-server-3.2.0\"},\"managedFields\":[{\"manager\":\"Go-http-client\",\"operation\":\"Update\", …
```

Explicitly set the value of RELEASE to a string

---

CHANGELOG.md
server/dashboard.js
server/db/db.js
server/mustache-templates/navPartial.mst
server/package-lock.json
server/package.json
server/routes.js

I just copied this functionality from Buttons and tweaked it to work for Sensors.
While testing, I discovered that I could download the CSV Export using a cookie from the browser even after I'd logged out using the "Log Out" button. So the `req.session.destroy()` call fixes that issue. The same thing came up in Buttons, so it's fixed in this PR: https://github.com/bravetechnologycoop/BraveButtons/pull/130 
- :heavy_check_mark: Deploy on `staging.sensors.brave.coop`
- :heavy_check_mark:  Show a copy of the results to Gordon and Oona and see what they think
- :heavy_check_mark: Run smoketests
- :heavy_check_mark: Make sure you can't download the CSV unless logged in
- :heavy_check_mark: Pushing the "Export CSV" button downloads a CSV file with the current datetime in the name
- …

Add "Export CSV" button to the Dashboard (CU-1mek79g)

---

README.md

Should have been included in the commit to start using a common branching schema.

Update README Travis badge link to main branch (CU-mn5q4g)

---

CHANGELOG.md
server/index.js
server/package-lock.json
server/package.json

- :heavy_check_mark: Deploy to Sensor Dev
- :heavy_check_mark: Run smoke tests
- :heavy_check_mark: Sanity check by creating a real alert using the Sensors in my bathroom and repsonding to it
- :heavy_check_mark: Run the Particle Accelerator and get back a ClickUp auth token

Add proxy endpoint for the Particle Accelerator to use ClickUp API (CU-21ghk0x)

---

CHANGELOG.md
server/db/031-add-session-and-sensors-vitals-indices.sql
server/db/db.js
server/setup_postgresql.sh

Two changes that may reduce our number of deadlocks:
1. Changed the list of tables that are locked during a transaction
- Added `sensors_vitals` because it must have been missed when this table was added in the previous release
- Removed `migrations` because it is only ever used by our migration script during deployments so should never get into a conflict in real life
1. Added indices on `sensors_vitals.locationid` and `sessions.locationid` because they are used as a join parameter in a number of long-running queries. By indexing them, these queries should run quicker. If they run quicker, then their transactions can end sooner, thus unlocking the tables sooner, and being less likely to cause another query to abort because it's waiting for the same resource and then assumes that it is in …

Try to fix deadlocks (CU-2atyr1z)

---

server/setup_postgresql.sh

- This was missed in PR: https://github.com/bravetechnologycoop/BraveSensor/pull/163

Remove Brave Siren column from the DB (CU-289wcj9)

---

CHANGELOG.md
server/README.md

Should i make a clickup task for this or is it ok?

Editted the README to improve the deployment instructions

---

CHANGELOG.md
firmware/boron-ins-fsm/.gitignore
firmware/boron-ins-fsm/inc/spark_wiring_string.cpp
firmware/boron-ins-fsm/inc/string_convert.cpp
firmware/boron-ins-fsm/inc/string_convert.h

Fixed an issue with string_convert function ultoa conflicting with stdlib function
Deleted commented out function to clean up code
Testing: Code compiles and unit tests pass

Added string_convert namespace for string_convert.cpp functions

---

CHANGELOG.md
firmware/README.md
server/README.md

- This fixes a bug with connectivity with AT&T in the US
- :heavy_check_mark: Deploy to my real Borons in the bathroom
- :heavy_check_mark: With my real Borons in the bathroom
- :heavy_check_mark: Trigger a Stillness Alert
- :heavy_check_mark: Trigger a second Stillness Alert
- :heavy_check_mark: Trigger a Duration Alert
- :heavy_check_mark: Run each of the cloud functions (update and echo)
- :heavy_check_mark: See publish when echoing the door sensor ID
- :heavy_check_mark: Restart and see that initial values in EEPROM are as expected
- :heavy_check_mark: See a heartbeat with state changes be sent

Upgrade firmware OS to 3.3.1 (CU-3aru0mb)

---

CHANGELOG.md
server/README.md
server/resources/translations/common.en.json
server/test/unit/vitalsTest/checkHeartbeatTest.js
server/vitals.js

i think 'yes' is happier than 'ok' - easier to translate 'yes'
test plan:
use postman to make another request and check text message to see if the change has been updated

fix typo in README and change responder message (CU-2q39wpk and CU-860pga04t)

---

server/smokeTest.js

forgotten extra bit from the pull request sc-add-api-key

add api key to smoke test

---

server/index.js

Fix smoketest

---

CHANGELOG.md
server/README.md

- And clarify a few other steps in the deployment instructions because they are things that I always do slightly differently when I'm really doing a deployment

Add Google link to README

---

.github/workflows/deploy-production.yml
CHANGELOG.md

- Added deploy workflow for new AWS production environment
- Added a check to see if the GH Ref is production branch
Note: Haven't been able to test the ref check, need this in main. If it doesn't work as expected then I can modify and test in a branch once this exists in main and open a new PR.

Production workflow

---

CHANGELOG.md
server/api.js
server/test/integration/apiTest/getAllSensorsTest.js
server/test/integration/apiTest/getSensorTest.js
server/test/unit/apiTest/authorizeTest.js

I noticed inconsistency in the way that the API authorize function was defined, so this task was to implement unit tests to ensure that the API authorize function works as intended.
Test plan:

Investigated API authorize function and added unit tests (CU-8678uuvjm)

---

.github/workflows/deploy-development.yml
.github/workflows/deploy-staging.yml
.travis.yml
CHANGELOG.md
server/README.md
server/package.json

- Because this is what we're moving towards and I don't want to forget any of the new steps

Add AWS DevOps instructions for Dev to README

---

CHANGELOG.md
firmware/boron-ins-fsm/clang-format-all.py
firmware/boron-ins-fsm/src/stateMachine.cpp
server/test/integration/vitalsTest/handleHeartbeatTest.js
server/vitals.js

Implements internal alert functionality with Sentry alerts triggered when a sensor's INS value is less than or equal to zero [CU8678v3y54](https://app.clickup.com/t/8678v3y54)
Test Plane:

Integrates internal alert system using Sentry, activating alerts when a sensor's INS value is equal to or less than zero (CU-8678v3y54).

---

CHANGELOG.md
firmware/boron-ins-fsm/src/BraveSensorProductionFirmware.ino
server/test/integration/vitalsTest/handleHeartbeatTest.js

After adding "isINSZero" to the heartbeat we didn't update the data object for the pre-existing heartbeat tests. For consistency, I added "isINSZero": false to all tests. I also added some spaces in one of the data objects to be consistent with rest of the test file. 
I also removed the extra space from my `BraveSensorProductionFirmware.ino` file so that Travis is passing.
**Test Plan:**

Update handleHeartbeatTest data (CU-8678y7w9y)

---

CHANGELOG.md
server/pa.js
server/package-lock.json
server/package.json

The previous PR for the PA Google API had an error in that requests that fail (Unauthorized, or Bad request) never resolved.
This PR fixes that.
Test Plan:

Fixed response for PA Google API in the event of failure

---

server/dashboard.js
server/db/db.js
server/pa.js
server/sensorAlerts.js
server/test/integration/dbTest/getActiveSensorClientsTest.js
server/test/unit/paTest/handleMessageClientsTest.js
server/vitals.js

Small fixes before database merge

---

server/BraveAlerterConfigurator.js
server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionByPhoneNumbersTest.js
server/test/integration/BraveAlerterConfiguratorTest/getAlertSessionTest.js
server/test/integration/BraveAlerterConfiguratorTest/getReturnMessageToRespondedByPhoneNumberTest.js
server/test/unit/BraveAlerterConfiguratorTest/alertSessionChangedCallbackTest.js

Update indexing to start at 0 (CU-86dth9zt2)

---

CHANGELOG.md
package-lock.json
server/db/050-update_incident_categories.sql
server/mustache-templates/newClient.mst

Updated the new client dashboard to reflect the new incident categories. Added a migration script to set the default value for incident categories.

update dashboard (CU-86du7hv9b)

---

server/setup_reporting_db.sh

From the output of the script:
This script is unsafe - it does the following:
1. It will download data from and slow the source database to a halt.
2. It will drop all necessary data and schemas from the destination database.
3. It will upload the downloaded data to the destination database.
Testing:

Create setup_reporting_db.sh for monthly data dumps (CU-86duh0eeu)

---

CHANGELOG.md
server/db/052-clientextensionaddon.sql
server/mustache-templates/clientPage.mst

Here are the updates needed to the DB,
Country - clients_extension.country (existing)
Country subdivision - clients_extension.country_subdivision (existing)
Building type - clients_extension.building_type (existing)
Funder - clients_extension.funder (NEW)
Project - clients_extension.project (NEW)
Parent org - clients_extension.organization; (NEW)
Client name - clients.display_name (existing)
City - clients_extension.city (NEW)
Zip Code/Postal Code - clients_extension.postal_code (NEW)
organization, funder, postal_code has been added by Elana, seen in script 50.
added script 52, to add the remaining fields.
There are 2 commits that I added to test the dev server, they cancel each other out. Changes in first commit.

Cc updateclienttables CU-86du6jp33

---

CHANGELOG.md
server/README.md

Updated README for password migration.

Cc pwmigrationreadme CU-86duhae9t

---

CHANGELOG.md
server/mustache-templates/landingPage.mst

Fixed minor issue with the landing page styling when it lists down all the clients. Now matches locations page and button dashboard.

Fix landing page styling (CU-86dup4ghg)

---

CHANGELOG.md
server/db/db.js
server/pa.js
server/routes.js

- Added new db function: getClientDevices to retrieve sensor information given client display_name.
- Created new server API endpoint: /pa/get-client-devices, that processes sensor information from db function and returns it on the route. This route will be used in the PA tool: Particle Client Functions.
Linked PR in particle-accelerator: [New PA tool: Client Particle Functions (CU-86due80fw).](https://github.com/bravetechnologycoop/particle-accelerator/pull/59)

Create new PA route for retrieving all sensors owned by a client (CU-86due80fw).

---

CHANGELOG.md
server/dashboard.js
server/db/db.js
server/mustache-templates/updateClient.mst

Fixed error caused due to updating client's first_device_live_at in dashboard.

Fix update client dashboard page for Sensors (CU-86dvqgum0)

---

CHANGELOG.md
server/src/db/db_new.js
server/src/sensorEvents.js
server/src/twilioEvents.js
server/src/utils/helpers.js
server/src/vitals.js
server/test/smokeTest.js

This PR improves the database concurrency by removing the table level locks for each transaction and rather shift to row level locks for frequent read-then-write database operations in our system. Combined with Postgres's automatic MVCC (multi version concurrency control) and now serialized transactions, the database operations are more concurrent.
- New database handlers for error, client connection, release, remove, and regular db logging.
- Added row level locks to some queries, preventing concurrent updates from different transactions.
- Made transaction level to serializable by default for safety.
- Max connections for db client pool increased to 50 for handling multiple concurrent transactions.
- Improved sentry logs for transaction errors.
- Removed the table-locking mechanism for …

Improve database concurrency (CU-86dw70vad)

---

CHANGELOG.md
server/src/dashboard.js
server/src/db/058-format-time-function.sql
server/src/db/db_new.js
server/src/mustache-templates/clientDetailsPage.mst
server/src/mustache-templates/funderProjectsPage.mst
server/src/mustache-templates/landingPage.mst
server/src/mustache-templates/organizationClientsPage.mst
server/src/mustache-templates/projectOrganizationsPage.mst
server/src/mustache-templates/updateDevicePage.mst
server/src/sensorEvents.js
server/src/utils/helpers.js
server/src/vitals.js

- Added migration script (58) that adds database function to format dates for dashboard.
- Added door last seen at in devices view for the dashboard.
- Optimized the dashboard rendering by parallelizing database calls.
- Updated url param handling for special characters using URIComponents.

Sensor dashboard update and fixes (CU-86dw9zbca)

---

CHANGELOG.md
server/src/db/db_new.js

- Fixed disconnection message bug.

Cc disconnection message fix

---

server/src/dashboard.js
server/src/db/db_new.js
server/src/mustache-templates/clientDetailsPage.mst
server/src/mustache-templates/newClientPage.mst
server/src/mustache-templates/updateClientPage.mst
server/test/factories_new.js
server/test/integration/dashboardTest/submitNewClientTest.js
server/test/integration/dashboardTest/submitUpdateClientTest.js

- Adjusted Create Client Page for MS teams fields
- Adjusted Update Client Page for MS teams fields
- Adjusted Client Details Page for MS teams fields

Cc ms teams dashboard

---

server/src/utils/helpers.js
server/src/utils/twilioHelpers.js
server/src/vitals.js

Screenshot of logs
Added functionality to check environment variables 
VITALS_START_TIME
VITALS_END_TIME
and only send alerts between these two times
Tested in dev environment

Cc vitals operating hours (CU-86dwbejz7)

---

firmware/boron-ins-fsm/Makefile
server/README.md

6.2.1 Firmware Update (CU-86dx3n9c6)
